DROP DATABASE IF EXISTS JOGOS;
CREATE DATABASE JOGOS;
USE JOGOS;

DROP TABLE IF EXISTS TABLE_tabuleiro_velha, TABLE_historico_partida_velha;

CREATE TABLE TABLE_tabuleiro_velha (
    LINHA INTEGER NOT NULL,
    COLUNA INTEGER NOT NULL,
    VALOR TEXT,
    PRIMARY KEY (LINHA, COLUNA)
);

CREATE TABLE TABLE_historico_partida_velha (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    JOGADOR TEXT NOT NULL,
    RESULTADO TEXT NOT NULL,
    DATA DATE NOT NULL
);

-- Inicializa o tabuleiro vazio
INSERT INTO TABLE_tabuleiro_velha (LINHA, COLUNA, VALOR) 
VALUES 
(1, 1, NULL),
(1, 2, NULL),
(1, 3, NULL),
(2, 1, NULL),
(2, 2, NULL),
(2, 3, NULL),
(3, 1, NULL),
(3, 2, NULL),
(3, 3, NULL);