# Generated by Django 5.2 on 2025-08-11 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_jogo', models.CharField(choices=[('single', 'Jogar Sozinho'), ('multi', 'Multijogador Local')], default='multi', max_length=20)),
                ('jogador_atual', models.CharField(default='X', max_length=1)),
                ('ativo', models.BooleanField(default=True)),
                ('vencedor', models.CharField(blank=True, max_length=1, null=True)),
                ('empate', models.BooleanField(default=False)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partida',
            },
        ),
        migrations.CreateModel(
            name='Tabuleiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.IntegerField()),
                ('coluna', models.IntegerField()),
                ('valor', models.CharField(choices=[('X', 'X'), ('O', 'O')], max_length=1)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tabuleiro',
                'unique_together': {('linha', 'coluna')},
            },
        ),
    ]
